version: '1.2'
services:
  postgres:
    platform: linux/arm64
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./persistence/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./persistence/schema:/db_scripts
  backend:
    build: back
    ports:
      - "8000:8000"
  frontend:
    build: front
    ports:
      - "3000:3000"